version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - ./gradlew dependencies
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -x test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes